characters = {
    "id":{
        "0":"Bday",
        "1":"Kiara",
        "2":"CaptainHat",
        "3":"Cole",
        "4":"Snapback",
        "5":"WashingMachine",
        "6":"DarkBday",
        "7":"Zoe",
        "8":"Forest",
        "9":"Fatcat",
        "A":"Insignia",
        "B":"KidCat",
        "C":"Gus",
        "D":"ProfessorGenius",
        "E":"HatGang",
        "F":"Random",
    },
    "character":{
        "Bday": {"name":"Birthday", "image":"Portrait_Bday.png"},
        "Kiara": {"name":"Kiara", "image":"Portrait_Kiara.png"},
        "CaptainHat": {"name":"Captain Hat", "image":"Portrait_CaptainHat.png"},
        "Cole": {"name":"Cole", "image":"Portrait_Cole.png"},
        "Snapback": {"name":"Snapback", "image":"Portrait_Snapback.png"},
        "WashingMachine": {"name":"Washing Machine", "image":"Portrait_WashingMachine.png"},
        "DarkBday": {"name":"DarkBirthday", "image":"Portrait_DarkBday.png"},
        "Zoe": {"name":"Zoe", "image":"Portrait_Zoe.png"},
        "Forest": {"name":"Forest", "image":"Portrait_Forest.png"},
        "Fatcat": {"name":"Fatcat", "image":"Portrait_Fatcat.png"},
        "Insignia": {"name":"Insignia", "image":"Portrait_Insignia.png"},
        "KidCat": {"name":"Kid Cat", "image":"portrait_kid_cat.png"},
        "Gus": {"name":"Gus & Buster", "image":"Portrait_Gus.png"},
        "ProfessorGenius": {"name":"Professor Genius", "image":"portrait_professor_genius.png"},
        "HatGang": {"name":"Hat Gang", "image":"portrait_hat_gang.png"},
        "Random": {"name":"Random", "image":"Portrait_Random.png"}
    }
}
