characters = {
    "id":{
        "0":"Bday",
        "1":"Kiara",
        "2":"CaptainHat",
        "3":"Cole",
        "4":"Snapback",
        "5":"WashingMachine",
        "6":"DarkBday",
        "7":"Zoe",
        "8":"Forest",
        "9":"Fatcat",
        "A":"Insignia",
        "B":"KidCat",
        "C":"Gus",
        "D":"ProfessorGenius",
        "E":"HatGang",
        "F":"Random",
    },
    "character":{
        "Bday": {"name":"Birthday", "image":"Portrait_Bday.png", "id":"0"},
        "Kiara": {"name":"Kiara", "image":"Portrait_Kiara.png", "id":"1"},
        "CaptainHat": {"name":"Captain Hat", "image":"Portrait_CaptainHat.png", "id":"2"},
        "Cole": {"name":"Cole", "image":"Portrait_Cole.png", "id":"3"},
        "Snapback": {"name":"Snapback", "image":"Portrait_Snapback.png", "id":"4"},
        "WashingMachine": {"name":"Washing Machine", "image":"Portrait_WashingMachine.png", "id":"5"},
        "DarkBday": {"name":"DarkBirthday", "image":"Portrait_DarkBday.png", "id":"6"},
        "Zoe": {"name":"Zoe", "image":"Portrait_Zoe.png", "id":"7"},
        "Forest": {"name":"Forest", "image":"Portrait_Forest.png", "id":"8"},
        "Fatcat": {"name":"Fatcat", "image":"Portrait_Fatcat.png", "id":"9"},
        "Insignia": {"name":"Insignia", "image":"Portrait_Insignia.png", "id":"A"},
        "KidCat": {"name":"Kid Cat", "image":"portrait_kid_cat.png", "id":"B"},
        "Gus": {"name":"Gus & Buster", "image":"Portrait_Gus.png", "id":"C"},
        "ProfessorGenius": {"name":"Professor Genius", "image":"portrait_professor_genius.png", "id":"D"},
        "HatGang": {"name":"Hat Gang", "image":"portrait_hat_gang.png", "id":"E"},
        "Random": {"name":"Random", "image":"Portrait_Random.png", "id":"F"}
    }
}
